[package]
name = "tessla_stdlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = { version = "15.1.0" }
once_cell = { version = "1.12.0" }

[lib]
name = "tessla_stdlib"
path = "src/lib.rs"